spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_boot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123
    hikari:
      minimum-idle: 4
      maximum-pool-size: 12
      idle-timeout: 600000

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000

logging:
  level:
    root: debug
    org:
      springframework:
        boot:
          autoconfigure: error
          web: error