server:
  port: 8060

spring:
  application:
    name:  my-boot
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: com.zrzyfw.myspringboot.modules.*.dao
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    banner: false
    db-config:
      id-type: UUID
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
